### ISSUE TITLE
fails to build with newer argon2

### ISSUE THREAD

**Issue by clinty** [ocharles/argon2#14]
https://github.com/P-H-C/phc-winner-argon2/commit/78d2a579fec204d7f50ecbe79e71ca33b6a60c1c dropped ARGON2_FLAG_CLEAR_MEMORY

**Comment by ocharles** [comment]
Can you have a look at http://hackage.haskell.org/package/cryptonite and see if the Argon 2 implementation there works for you? I am looking to deprecate this package.

**Comment by clinty** [comment]
I thought we needed this for a reverse dependency but apparently we don't.

**Comment by clinty** [comment]
Ah, it's for keysafe.

**Comment by ocharles** [comment]
Ok, I'm going to email Joey about moving to cryptonite.

**Comment by clinty** [comment]
Sounds good.

**Comment by spwhitton** [comment]
I contacted Joey, too, and he says that it would be non-trivial to port keysafe because cryptonite does not have an equivalent of the `hashEncoded` function of this library.  Could that be added?

**Comment by ocharles** [comment]
@vincenthz - could it?

**Comment by hvr** [comment]
@ocharles Please don't deprecate this library. If this started depending on cryptonite I wouldn't be able to use it anymore as it would be hopeless to get it past code-audit. :-(

**Comment by ocharles** [comment]
Happy to pass on maintainership, but I don't have the time to commit to the
attention this project deserves.

**Comment by hvr** [comment]
@ocharles I'd be happy to take over maintainership!

**Comment by ocharles** [comment]
@hvr added you as a contributor on here and a maintainer on Hackage. Go forth and hack! It's yours now, don't worry about running things past me.
