### ISSUE TITLE
can I join the maintainers

### ISSUE THREAD

**Issue by cdornan** [ocharles/argon2#17]
I would be happy the help maintain this package -- starting with a update/revision for ghc-9.2.1 (base-4.16.*, bytestring-0.11.*).

**Comment by ocharles** [comment]
I've added you as a maintainer on Hackage, but @haskell-hvr will need to grant you commit rights here (I can't do that).

**Comment by galenhuntington** [comment]
I don't know if there's a better place to bring this up, but as of GHC 9.4, base is now at 4.17.

**Comment by cdornan** [comment]
(now revised to allow 4.17)
