### ISSUE TITLE
Feature request: Make outLen an argument

### ISSUE THREAD

**Issue by patrickmn** [ocharles/argon2#9]
I needed to use this to do password-based key derivation of a 32-byte key (for NaCl) and had to semi-fork the code to allow a user-defined outLen. (It didn't seem quite custom enough to warrant using the FFI bindings directly.)

Since adding an outLen parameter to the existing hash functions would break the API, perhaps it could be added as separate functions?

Very happy to send a pull request if you'd like.

**Comment by ocharles** [comment]
I'm afraid what you're suggesting is beyond me, but if you think it's OK (safe?) to add a separate function to do this, I will be happy to accept a pull request.

**Comment by ocharles** [comment]
I won't be changing this myself, but I will still accept a PR if this is important to people.
